spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_security?characterEncoding=utf-8&serverTimeZone=UTC
    username: root
    password: fqh
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml